Improoved GUI for Read and Create Activity
angelopetraccaro/PlaceOfInterest-Repository pull request #5
Opened 2020-12-05 19:00 UTC by francescosaccone

2020-12-05 19:07 UTC, Antonio04-cmyk commented on PlacesOfInterest/app/src/main/java/com/gmail/petraccaro/angelo/placesofinterest/CreateActivity.java
> +            if( uriFoto != null || br != null || nm != null || ds != null || item != null) {
????

2020-12-05 19:10 UTC, Antonio04-cmyk commented on PlacesOfInterest/app/src/main/java/com/gmail/petraccaro/angelo/placesofinterest/CreateActivity.java
> +                        Toast.makeText(CreateActivity.this, "Attenzione,scegli o scatta una foto!Cafone", Toast.LENGTH_SHORT).show();
write less, code more

2020-12-05 19:13 UTC, angelopetraccaro commented on PlacesOfInterest/app/src/main/java/com/gmail/petraccaro/angelo/placesofinterest/CreateActivity.java
> +            if( uriFoto != null || br != null || nm != null || ds != null || item != null) {
In questa condizione sostituisci con &&. (Considerando che bisogna poi inserire tutti i campi presenti nella condizione per non far fallire l'aggiunta)

2020-12-05 19:13 UTC, angelopetraccaro commented on PlacesOfInterest/app/src/main/java/com/gmail/petraccaro/angelo/placesofinterest/CreateActivity.java
> +                //  Double lon = Double.parseDouble(lg);
remember to clean up the comments

2020-12-05 19:14 UTC, Antonio04-cmyk commented on PlacesOfInterest/app/src/main/java/com/gmail/petraccaro/angelo/placesofinterest/CreateActivity.java
> +            if( uriFoto != null || br != null || nm != null || ds != null || item != null) {
write less, code more

2020-12-05 19:15 UTC, Antonio04-cmyk requested changes
ok , I'm not  agree with this changes

2020-12-06 17:15 UTC, francescosaccone commented
Ok!

2020-12-06 17:15 UTC, closed without merging